on: [push, pull_request, workflow_dispatch]
name: Test

jobs:
  test:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    env:
      GO111MODULE: on

    steps:
    - name: Install Go
      uses: actions/setup-go@main
      with:
#         go-version: 1.16
        cache: false

    - name: Go environment
      run: |
        go version
        go env
        echo "PATH is $PATH"
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Run tests
      run: |
        go test -race -v ./...
      shell: bash

    - name: Check gofmt
      run: |
        gofmt -l .
        test `gofmt -l . | wc -l` = 0
      shell: bash
  test-v2:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    env:
      GO111MODULE: on

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Go environment
      run: |
        go version
        go env
        echo PATH is $PATH
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Run tests
      run: |
        go test -race -v ./...
      shell: bash

    - name: Check gofmt
      run: |
        gofmt -l .
        test `gofmt -l . | wc -l` = 0
      shell: bash
      
  test-custom:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    env:
      GO111MODULE: on

    steps:
    - name: Install Go
      uses: dominikh/setup-go@pattern
      with:
        go-version: ${{ matrix.go-version }}

    - name: Go environment
      run: |
        go version
        go env
        echo PATH is $PATH
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Run tests
      run: |
        go test -race -v ./...
      shell: bash

    - name: Check gofmt
      run: |
        gofmt -l .
        test `gofmt -l . | wc -l` = 0
      shell: bash
